Added test llama-2-7b with GPTQ quant. scheme
huggingface/optimum-benchmark pull request #141
Opened 2024-02-29 14:55 UTC by lopozz

test TheBloke/Llama-2-7B-GPTQ with pytorch backend and cuda hardware.

2024-03-01 02:41 UTC, IlyasMoutawwakil commented
Thanks a lot for the PR ! I have few suggestions:
- let's use `TheBloke/TinyLlama-1.1B-Chat-v0.3-GPTQ` to reduce download time like in [trt-llm](https://github.com/huggingface/optimum-benchmark/blob/main/tests/configs/tensorrt_llm.yaml#L14) (this is just the smallest llama I can think of)
- let's use the compose api, ie inherit stuff from other configs instead of rewriting them like [here](https://github.com/huggingface/optimum-benchmark/blob/main/tests/configs/cpu_inference_pytorch_gpt_sweep.yaml).

2024-03-01 14:43 UTC, lopozz commented
Hi thanks for the feedback. Should I create a default file for llama like it was done for _gpt_ or _timm_? Also I am currently working with a machine with one GPU. hence, the backend.device_ids: 0

2024-03-04 07:06 UTC, IlyasMoutawwakil commented
no need, just reuse the ones already provided as much as possible and explicit the rest:
```yaml
defaults:
  - backend: pytorch # default backend
  # order of inheritance, last one overrides previous ones
  - _base_ # inherits from base config
  - _inference_ # inherits from inference config
  - _cuda_ # inherits from cuda config
  - _self_ # hydra 1.1 compatibility

experiment_name: cuda_inference_pytorch_gptq

backend:
  model: TheBloke/TinyLlama-1.1B-Chat-v0.3-GPTQ
  quantization_config:
    exllama_config:
      version: 2

hydra:
  sweeper:
    params:
      backend.no_weights: true,false
```

2024-03-06 11:04 UTC, lopozz commented
Hi @IlyasMoutawwakil I just modifid the file with your feedback. Let me know if I can do something else

2024-03-08 17:43 UTC, IlyasMoutawwakil commented
@lopozz thanks, can you also add the pip installation to the test workflow

2024-03-13 18:12 UTC, lopozz commented
Thanks for the support @IlyasMoutawwakil, it is my first pull request, but I think I solved the issue. Also, seeing the comment https://github.com/huggingface/optimum-benchmark/pull/144#issuecomment-1981232399 I did not modify the setup.py

Main changes: pip installation of optimum and auto-gptq packages

Let me know if you have further feedback.

2024-03-15 09:11 UTC, IlyasMoutawwakil commented
@lopozz thanks a lot for working on this.
`optimum` and `auto-gptq` are still missing from `setup.py`'s extras.
I would suggest not adding `optimum` as a standalone but rather grouping both deps in `auto-gptq`
```python
    "bitsandbytes": ["bitsandbytes"],
    "auto-gptq": ["optimum", "auto-gptq"],
```
This will probably not work with ROCm 5.6 & 5.7 and CUDA 11.8 😅 as for these systems an extra url is required to download the right wheels, as explained in: https://github.com/AutoGPTQ/AutoGPTQ?tab=readme-ov-file#installation
It can be solved using `dependency_links` as explained in https://stackoverflow.com/a/30064248, but tell me if this is too complicated for the scope of your PR.

2024-03-19 16:39 UTC, lopozz commented
@IlyasMoutawwakil 
update of the last commit:

- added 3 new identifiers in setup.py for cuda121, cuda118 and rocm to install optimum and auto-gptq according to the corresponding index urls.

I did not used dependency_links as you suggested because deprecated starting with pip version 19.0 (released 2019-01-22) https://setuptools.pypa.io/en/latest/deprecated/dependency_links.html#specifying-dependencies-that-aren-t-in-pypi-via-dependency-links. Let me know if you agree, in case I can modify it.

2024-03-20 09:25 UTC, IlyasMoutawwakil requested changes

2024-03-20 09:25 UTC, IlyasMoutawwakil commented on setup.py
>  }
this won't work for rocm 5.6, let's just remove it and remove gptq tests on rocm ci by adding `and not gptq` to pytest keywords

2024-03-20 09:25 UTC, IlyasMoutawwakil commented on Makefile
> +CLI_ROCM_PYTORCH_REQS := testing,timm,diffusers,deepspeed,peft,autoawq,auto-gptq-rocm
no need

2024-03-20 09:25 UTC, IlyasMoutawwakil commented on .github/workflows/test_cli_rocm_pytorch.yaml
> +          -c "pip install requests && pip install -e .[testing,diffusers,timm,deepspeed,peft,autoawq-rocm] && pytest -k 'cli and cuda and pytorch and not bnb' -x"
let's add `and not gptq`

2024-03-20 09:33 UTC, IlyasMoutawwakil commented
Thanks, I left some comments, don't forget to run styling. 
There appear to be a `SIGSEGV` when testing GPTQ, probably something wrong with the cleanup code, I'll investigate the cause of that.

2024-03-20 10:10 UTC, IlyasMoutawwakil commented
okay found why, in the code I uses `exllama_version` in `exllama_config` but it's supposed to be just `version`.
will fix that in another PR and merge it quickly.

2024-03-20 10:49 UTC, IlyasMoutawwakil commented
fixed in #165

2024-03-21 08:21 UTC, IlyasMoutawwakil commented
Thanks for addition @lopozz great work on your first PR 🤗

2024-03-21 08:22 UTC, IlyasMoutawwakil approved these changes

2024-03-21 08:29 UTC, merged