Refactor llm perf backend handling
huggingface/optimum-benchmark pull request #258
Opened 2024-09-10 13:34 UTC by baptistecolle

2024-09-17 12:02 UTC, IlyasMoutawwakil commented
is this PR ready ?

2024-09-17 12:42 UTC, baptistecolle commented
Yes, but some workflows are broken on main so I am fixing them first so that the workflows can be tested on this PR. That's why I left it as a draft PR for now. Let me know if you prefer I do things differently for next time :)

2024-09-23 07:15 UTC, baptistecolle commented
I also added the new label system to the leaderboard, you can trigger it via the `leaderboard` label

2024-09-23 07:23 UTC, IlyasMoutawwakil commented on .github/workflows/update_llm_perf_cpu_pytorch.yaml
> +      contains( github.event.pull_request.labels.*.name, 'leaderboard')}}
you can probably add more specifications here to be able to run specific benchmarks, like `cuda`/`cpu`
didn't try it, but you might also be able to add conditions on matrix arguments, like `|| contains( github.event.pull_request.labels.*.name, matrix.subset)}}` to run specific subsets or specific machines

2024-09-23 07:26 UTC, IlyasMoutawwakil commented on llm_perf/benchmark_runners/update_llm_perf_cuda_pytorch.py
> +        super().__init__(backend="pytorch", hardware="cuda")
I would prefer `device="cuda"` to not confuse terminologies, optimum-benchmark already has a terminology and it's better to not make it ambiguous.

2024-09-23 07:31 UTC, IlyasMoutawwakil commented on llm_perf/common/benchmark_runner.py
> +class BenchmarkRunner(ABC):
not a fan of using the keyword runner here, maybe an LLMPerfBenchmarkManager, no strong opinion on this tho

2024-09-23 07:31 UTC, IlyasMoutawwakil commented on llm_perf/common/benchmark_runner.py
> +        self.weights_configs = self._get_weights_configs(self.subset)
this is very specific for pytorch backend, I don't see it holding once more backends are introduced

2024-09-23 07:35 UTC, IlyasMoutawwakil commented on llm_perf/common/benchmark_runner.py
> +            return
won't hold for other backends as their configuration will be in term of optimizations and quantization schemes to use

2024-09-23 07:50 UTC, IlyasMoutawwakil requested changes
I like the hardware class which registers info about the hardware configs we deal with.
The `BenchmarkRunner` class seems to me that it'll make things convoluted a bit, with less readability. The benefit of the one file script design is that it showcases how simple and linear it is to conduct benchmarks (like a model fine-tuning recipe), similar to [transformers examples](https://github.com/huggingface/transformers/tree/main/examples/pytorch). One might argue that we could group examples in a class called `ExamplesRunner` but for a user who wanna reproduce results by reading and running a simple script, it complicates things.
But if this is truly what will make it simpler for you to add more benchmarks to the leaderboard, I have no issue with it. @regisss

2024-09-23 08:55 UTC, baptistecolle commented
> I like the hardware class which registers info about the hardware configs we deal with. The `BenchmarkRunner` class seems to me that it'll make things convoluted a bit, with less readability. The benefit of the one file script design is that it showcases how simple and linear it is to conduct benchmarks (like a model fine-tuning recipe), similar to [transformers examples](https://github.com/huggingface/transformers/tree/main/examples/pytorch). One might argue that we could group examples in a class called `ExamplesRunner` but for a user who wanna reproduce results by reading and running a simple script, it complicates things. But if this is truly what will make it simpler for you to add more benchmarks to the leaderboard, I have no issue with it. @regisss

The main idea of abstracting some of the logic for the llm-perf leaderboard code is to prevent code duplication between all the different benchmarking codes. This should speed up development and also facilitate maintainability. 

I agree it would be nice to run a simple script to get the results from the leaderboard.  It is still possible to run the benchmarks after cloning the repo and doing `python llm_perf/benchmarks_runners/update_llm_perf_cpu_pytorch.py`. A later version of the llm-perf code could include a CLI like optimum-benchmark for the best user experience. The code could include a list of `.yaml` examples for the llm-perf to define a way to run the tests of the leaderboard on your own hardware e.g. `llm_perf --config-dir examples/ --config-name cuda_pytorch`. Lastly,  the current scripts are only used for internal purposes (to update the leaderboard) so I think making the current setup a bit more complex is fine

2024-09-23 09:11 UTC, IlyasMoutawwakil commented
there's also the fact that its compute is scaling and I think it's better if it's contained so that it wouldn't slow down or throttle the development CI of optimum-benchmark.

2024-09-23 09:30 UTC, baptistecolle commented
> yeh i see your point, it's just that I moved the llm-perf into a folder in optimum-benchmark based on the idea that it's just a couple of scripts that don't require a lot of maintenance and work as an example of usage of optimum-benchmark, but if the plan is to make it a more complex project then maybe it's time for it to have its own repo again, to ease its development for you. wdyt ? old repo: https://github.com/IlyasMoutawwakil/llm-perf-backend/tree/00340abbdcd3ba96c07e2ac3c615f00cb6053c53

Good question...
From a repo perceptive if the llm-perf leaderboard becomes bigger and more complex it add a lot of complexity inside optimum-benchmark which is not necessary. You can also view the leaderboard as a extension of optimum-benchmark as being the `optimum-benchmark-leaderboard` thus having both project in the same repo could make sense to keep them aligned.
What are the main reasons you stopped having a separate repo and merge it into this one? @IlyasMoutawwakil As the main maintainer of optimum-benchmark do you have a preference?

Also @regisss do you have an opinion on the matter?

2024-09-23 09:54 UTC, IlyasMoutawwakil commented
> What are the main reasons you stopped having a separate repo and merge it into this one?

> I moved the llm-perf into a folder in optimum-benchmark based on the idea that it's just a couple of scripts that don't require a lot of maintenance and work as an example of usage of optimum-benchmark

it was for the reason above, and for faster development as optimum-benchmark was changing at a higher rate (before pypi release and transformers adoption). 
I also wanted to have access to the runners in the optimum-benchmark repo which were not accessible in my personal profile.

> You can also view the leaderboard as a extension of optimum-benchmark as being the optimum-benchmark-leaderboard thus having both project in the same repo could make sense to keep them aligned.

It's mostly using the cli/api interface which we're keeping consistent across releases, so I don't see any alignment issues.

> @IlyasMoutawwakil As the main maintainer of optimum-benchmark do you have a preference?

I think a separation of package and application makes more sense, like [`lighteval`](https://github.com/huggingface/lighteval) and [`llm-leaderboard-backend`](https://github.com/huggingface/llm-leaderboard-backend)

2024-09-24 13:29 UTC, baptistecolle commented
OK then I will do a separate backend for the llm-perf! I will make another PR this week, to remove the current llm-perf logic from optimum-benchmark as this won't be needed anymore

2024-09-24 13:29 UTC, closed without merging

2024-09-24 16:30 UTC, IlyasMoutawwakil commented
awesome ! and don't hesitate to ping me for reviews if needed.